version: 1

services:
  www:
    path: apps/www
    envFile: apps/www/.vercel/.env.development.local
  www-search:
    path: apps/www-search
    envFile: apps/www-search/.vercel/.env.development.local
  auth:
    path: apps/auth
    envFile: apps/auth/.vercel/.env.development.local
  chat:
    path: apps/chat
    envFile: apps/chat/.vercel/.env.development.local
  console:
    path: apps/console
    envFile: apps/console/.vercel/.env.development.local

worktrees:
  path: ./worktrees

hooks:
  postWorktreeCreate: 
  - nextjs-apps-port-remap.sh
